src/PaymentBundle/Entity/Cart.php
<?php

namespace PaymentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use PromotionBundle\Entity\Catalog;
use PromotionBundle\Entity\CouponKind;
use PromotionBundle\Entity\CouponRange;

/**
 * Cart
 *
 * @ORM\Table(name="bp_cart")
 * @ORM\Entity(repositoryClass="PaymentBundle\Repository\CartRepository")
 */
class Cart {

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="carts")
     * @ORM\JoinColumn(nullable=true,onDelete="CASCADE")
     */
    protected $user;

    /**
     * @var CommandeCatalog
     * @ORM\OneToMany(targetEntity="PromotionBundle\Entity\CommandeCatalog", mappedBy="cart", cascade={"persist", "remove"})
     */
    protected $commandeCatalogs;

    /**
     * @ORM\ManyToOne(targetEntity="PromotionBundle\Entity\Coupon", inversedBy="carts", cascade={"persist"})
     */
    protected $coupon;

    /**
     * @var Payment
     * @ORM\OneToOne(targetEntity="PaymentBundle\Entity\Payment", mappedBy="cart", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true,onDelete="CASCADE")
     */
    protected $payment;

    private $tauxTva = 0.2;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    protected $updatedAt;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set paid
     *
     * @param Payment $payment
     *
     * @return Cart
     */
    public function setPayment($payment) {
        $this->payment = $payment;

        return $this;
    }

    /**
     * Get paid
     *
     * @return Payment
     */
    public function getPayment() {
        return $this->payment;
    }

    /**
     * Set user
     *
     * @param \UserBundle\Entity\User $user
     *
     * @return Cart
     */
    public function setUser(\UserBundle\Entity\User $user = null) {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \UserBundle\Entity\User
     */
    public function getUser() {
        return $this->user;
    }

    /**
     * Add commandeCatalog
     *
     * @param \PromotionBundle\Entity\CommandeCatalog $commandeCatalog
     *
     * @return BusinessPlan
     */
    public function addCommandeCatalog(\PromotionBundle\Entity\CommandeCatalog $commandeCatalog) {
        $this->commandeCatalogs[] = $commandeCatalog;

        return $this;
    }

    /**
     * Remove commandeCatalog
     *
     * @param \PromotionBundle\Entity\CommandeCatalog $commandeCatalog
     */
    public function removeCommandeCatalog(\PromotionBundle\Entity\CommandeCatalog $commandeCatalog) {
        $this->commandeCatalogs->removeElement($commandeCatalog);
    }

    /**
     * Get commandeCatalogs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCommandeCatalogs() {
        return $this->commandeCatalogs;
    }

    public function checkCartIntegrity() {
        if ($this->getCommandeCatalogs()) {
            foreach ($this->getCommandeCatalogs() as $commandeCatalog) {
                try {
                    $commandeCatalog->getCatalog()->getName();
                } catch (\Doctrine\ORM\EntityNotFoundException $e) {
                    $this->removeCommandeCatalog($commandeCatalog);
                }
            }
        }
    }
    /**
     * Get total cart amount HT
     *
     * @return flaot
     */
    public function getTotalAmountHT() {
        return $this->getTotalAmountTTC() / (1 + $this->tauxTva);
    }

    /**
     * Get total cart amount TTC
     *
     * @return float
     */
    public function getTotalAmountTTC() {
        $total = 0;
        if ($this->commandeCatalogs != null) {
            foreach ($this->commandeCatalogs as $commandeCatalog) {
                $total += $commandeCatalog->getCatalog()->getPrice() * $commandeCatalog->getQuantity();
            }
        }

        return $total - $this->getReductionAmountTTC();
    }

    /**
     * Get reduction amount
     *
     * @return float
     */
    public function getReductionAmountTTC() {
        $reduction = 0;
        $amountBP = 0;
        $amountOptions = 0;

        if ($this->commandeCatalogs != null) {
            foreach ($this->commandeCatalogs as $commandeCatalog) {
                if ($commandeCatalog->getCatalog()->getType() === Catalog::CATALOG_TYPE_BP) {
                    $amountBP = $commandeCatalog->getCatalog()->getPrice();
                } else {
                    $amountOptions = $commandeCatalog->getCatalog()->getPrice() * $commandeCatalog->getQuantity();
                }
            }
        }

        $amountTotal = $amountBP + $amountOptions;

        if ($this->coupon != null) {
            switch ($this->coupon->getRange()) {
            case CouponRange::BP_ONLY:
                $assiette = $amountBP;
                break;
            case CouponRange::CART:
                $assiette = $amountTotal;
                break;
            case CouponRange::OPTIONS_ONLY:
                $assiette = $amountOptions;
                break;
            }

            switch ($this->coupon->getKind()) {
            case CouponKind::AMOUNT:
                if ($assiette - $this->coupon->getValue() > 0) {
                    $reduction = $this->coupon->getValue();
                } else {
                    $reduction = $assiette;
                }
                break;
            case CouponKind::PERCENT:
                $reduction = $assiette * $this->coupon->getValue() / 100;
                break;
            }
        }

        return $reduction;
    }

    /**
     * Get tva amount
     *
     * @return float
     */
    public function getTVA() {
        return $this->getTotalAmountTTC() - $this->getTotalAmountHT();
    }

    public function getCoupon() {
        return $this->coupon;
    }

    public function setCoupon($coupon) {
        $this->coupon = $coupon;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Cart
     */
    public function setCreatedAt($createdAt) {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt() {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Cart
     */
    public function setUpdatedAt($updatedAt) {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt() {
        return $this->updatedAt;
    }

}

src/PaymentBundle/Controller/CartController.php
<?php

/**
 * Created by PhpStorm.
 * User: wac28
 * Date: 10/10/16
 * Time: 16:56
 */

namespace PaymentBundle\Controller;

use PaymentBundle\Entity\Payment;
use PaymentBundle\Form\PaymentType;
use PaymentBundle\Service\CartService;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class CartController extends Controller {

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Request $request) {
        $em = $this->getDoctrine()->getManager();

        $referer = $request->headers->get('referer');
        // $session = $request->getSession()->set('purchase_origin', $referer);
        
        $cartService = $this->container->get(CartService::class);
        $cartService->storeReferer($request);

        $cart = $cartService->getCurrentCart($this->getUser());

        //configure payment
        $payment = new Payment();
        $payment->setStatut(Payment::PAYMENT_STATUT_INITIATE);
        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);

        return $this->render('PaymentBundle:Cart:index.html.twig', [
            'user' => $this->getUser(),
            'cart' => $cart,
        ]);
    }

}

src/PaymentBundle/Resources/views/Cart/index.html.twig
{% extends '::Frontend/layout.html.twig' %}

{% set header = "Récapitulatif de votre panier"%}

{% set nbArticles = 0 %}
{% for commandeCatalog in cart.commandeCatalogs %}
    {% set nbArticles = nbArticles+commandeCatalog.quantity %}
{% endfor %}


{% block body %}
    <div
        class="col s12 m10 offset-m1">
        <!-- FORM STEP 1 BP -->

        <div class="row">
            <div class="col s10 offset-s1">
            Pour le règlement de votre formule vous allez être redirigé vers notre partenaire financier « Stripe ». Un environnement parfaitement sécurisé.
            </div>
        </div>
        
        {% set step = 0 %}
        <div class="row">
            <div class="col s10 offset-s1">
                {% set step = step + 1 %}
                <h5 class="flow-text black-text">{{step}}
                    - Formule</h5><hr>
                <div class="row center">
                    {% include 'PaymentBundle::Cart\\purchase_lines.html.twig' %}
                </div>

                {% set step = step + 1 %}
                <div class="row">
                    <h5 class="flow-text black-text">{{step}}
                        - Bon d'achat / Promotion
                    </h5><hr>
                    {% include 'PaymentBundle::Cart\\vouchers.html.twig' %}
                </div>
                <div
                    class="row">
                    <!--==== total ====-->
                    <div class="col s12">
                        <h5 class="flow-text black-text">Total TTC<span id="total-price" class="right">
                                {% if cart.totalAmountTTC == 0 %}Gratuit
                                {% else %}
                                    {{ cart.totalAmountTTC|formatNumber('€',2) }}
                                {% endif %}
                            </span>
                        </h5><hr>
                        <div class="">Dont TVA<span id="total-price" class="right">{{ cart.tva|formatNumber('€',2) }}</span>
                        </div>
                        <div class="">Total HT<span id="total-price" class="right">{{ cart.totalAmountHT|formatNumber('€',2) }}</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 right-align">
                        <label>
                            <input type="checkbox" id="cgvAccepted" name="cgvAccepted" value="on"/>
                            <span for="cgvAccepted" text-align="right">J'ai lu et j'accepte les
                                <a class="izy-color-primary-font" target="_blank" href="https://planoo.ai/cgu-cgv/">Conditions Générales de Vente</a>.</span>
                        </label>
                    </div>
                    <div class="row">
                        <div
                            class="row">
                            <!--button-->
                            <div class="input-field col s12">
                                {% if nbArticles == 0 %}
                                    <a href="{{ path('user_my_projects') }}" class="btn-large izy-color-primary-light-bg waves-effect waves-light right z-depth-0">Annuler (Aucune formule selectionnée)</a>
                                {% else %}
                                    {% if cart.totalAmountTTC > 0 %}
                                        <div class="tooltipped div-cgv-needed right" data-tooltip="Veuillez accepter les Conditions Générales de Vente" data-position="left">
                                            <a href="{{ path('payment_stripe_checkout_form', {cartId: cart.id}) }}" class="btn-cgv-needed disabled btn-large izy-color-secondary-bg waves-effect waves-light right z-depth-0" type="submit" name="action">Payez</a>
                                        </div>
                                    {% elseif nbArticles > 0 %}
                                        <div class="tooltipped div-cgv-needed right" data-tooltip="Veuillez accepter les Conditions Générales de Vente" data-position="left">
                                            <a href="{{ path('payment_freemium', {id: cart.id}) }}" onclick="sendPurchaseEventToGTM();" class="btn-cgv-needed disabled btn-large izy-color-primary-bg waves-effect waves-light right z-depth-0" type="submit" name="action">Valider</a>
                                        </div>
                                    {% else %}
                                        <a href="{{ path('user_my_projects') }}" class="btn-large izy-color-primary-light-bg waves-effect waves-light right z-depth-0">Annuler (panier vide)</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

{% block javascripts %}
    {{ parent() }}

    <script src='{{ asset("bundles/fosjsrouting/js/router.js") }}'></script>
    <script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>

    <script>
        $( function () {
            $( "#cgvAccepted" ).bind( "change", function ( event ) {
                var isChecked = $( event.currentTarget ).is( ":checked" );
                $( ".btn-cgv-needed" ).each( function () {
                    if ( isChecked ) {
                        $( this ).removeClass( "disabled" );
                    } else {
                        $( this ).addClass( "disabled" );
                    }
                } );
                $( ".material-tooltip" ).each( function () {
                    if ( isChecked ) {
                        $( this ).css( "display", "none" );
                    } else {
                        $( this ).css( "display", "block" );
                    }
                } );
            } );
        } );
    </script>
{% endblock javascripts %}

src/PaymentBundle/Resources/views/Cart/purchase_lines.html.twig
<table class="table">
    <thead>
        <tr>
            <th>Formule</th>
            <th class="center-align">Prix unitaire</th>
            <th class="center-align">Supprimer</th>
        </tr>
    </thead>

    <tbody>
        {% for commandeCatalog in cart.commandeCatalogs %}
            <tr>
                <td>
                    <div class="bold">{{ commandeCatalog.catalog.name|raw }}</div>
                    {% if commandeCatalog.businessPlan %}
                        <i class="purchase-line-bp">Business plan associé :
                            {{commandeCatalog.businessPlan.getDisplayName()}}</i>
                    {% endif %}
                </td>
                <td class="center-align">{{ commandeCatalog.catalog.price }}€</td>

                <td class="center-align">
                    <a href="{{path('promotion_catalog_remove_item', {'itemId': commandeCatalog.catalog.id, 'idCart': cart.id })}}" class="right btn-floating cart waves-effect izy-color-primary-dark-bg izy-color-primary-fg">
                        <i class="material-icons">clear</i>
                    </a>
                    {# <form action="#">
                        <p>
                            <label>
                                <input class="with-gap" name="group1" type="radio" onclick="location.href = '{{ path('promotion_catalog_add_item', {'cartId': cart.id,'itemId': commandeCatalog.catalog.id}) }}'"/>
                                <span>&nbsp;</span>
                            </label>
                        </p>
                    </form> #}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

src/PaymentBundle/Resources/views/Cart/vouchers.html.twig
{% for message in app.flashes('couponError') %}
    <div class="row ">
        <div class="col s12">
            <div class="card red lighten-5 z-depth-0">
                <div class="card-content red-text">
                    <p>
                        <i class="material-icons left">error</i>
                        {{ message }}</p>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
<table>
    <thead>
        <tr>
            <th>Promotion</th>
            <th>Code</th>
            <th width="120px" class="center-align">Reduction TTC</th>
            <th width="20px"/>
        </tr>
    </thead>

    <tbody>
        {% if cart.coupon is not null %}
            <tr>
                <td>{{ cart.coupon.name }}</td>
                <td>{{ cart.coupon.code }}</td>
                <td class="center-align">{{ cart.reductionAmountTTC|formatNumber('€',2) }}</td>
                <td class="center-align">
                    <a href="{{path('promotion_coupon_remove', {'idCoupon' :cart.coupon.id ,'idCart':cart.id })}}" class="right btn-floating cart waves-effect izy-color-primary-dark-bg izy-color-primary-fg">
                        <i class="material-icons">clear</i>
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td>Aucune promotion</td>
                <td/>
                <td class="center-align">0€</td>
            </tr>
        {% endif %}
    </tbody>
</table>
<form action="{{ path('promotion_coupon_checker') }}" method="POST">
    <div
        class="row">
        <!-- capital social-->
        <div class="input-field col offset-m5 m5 s10">
            <i class="material-icons prefix grey-text">loyalty</i>
            <input id="amount" type="text" class="validate cart-promo-form-field" name="code">
            <label for="amount">Code promotionnel</label>
        </div>
        <div class="input-field col s2">
            <button type="submit" class="btn izy-color-primary-bg waves-effect waves-light right z-depth-0">
                utiliser
            </button>
        </div>

    </div>
</form>